[package]
name = "xcoin"
version = "0.0.0"
authors = ["Ian Macalinao <ian@aptos.is>"]
license = "Apache-2.0"

[readme]
title = "XCoin by Aptos.is"

[addresses]
xcoin_deployer = "0x156bf4547b14bb360c46880976ac87987e7ada3aa9477596f3001e3288195533"
xcoin = "0x69718ef82997b31b7c1612cbc6b7eb0e3224897e631506d9675888b71f0c775a"

[dependencies.MoveStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
subdir = "aptos-move/framework/move-stdlib"
rev = "a3143756d498821f4f51a5970c7ea35d483938b3"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
subdir = "aptos-move/framework/aptos-framework"
rev = "a3143756d498821f4f51a5970c7ea35d483938b3"

[dependencies.deployer]
git = "https://github.com/DeployDAO/aptos-deployer.git"
rev = "e40240fce3c15eab6de511337645d6f700d81c9a"

[dev-dependencies.aptest]
git = "https://github.com/aptosis/aptest.git"
rev = "484d2089f894b174603a36329454818a0453a657"
